config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, path: :admin_users, only: [:index, :create, :update, :destroy]
  resources :log_entries, only: [:index, :create, :update, :destroy]
  resources :authentication_tokens, only: [:index, :destroy]
  resources :instances, only: [:index, :create, :update, :destroy]
  resources :toilet_definitions, only: [:index, :create, :update, :destroy]
  namespace :api do
    resources :log_entries, only: [:index, :create, :show, :update, :destroy] do
      collection do
        get :top
        get :activations
      end
    end
    resources :ranking, only: :none do
      collection do
        get :top
        get :my
      end
    end
    resources :toilet_definitions, only: [:index]
    resources :users, only: :none do
      collection do
        get :me
        put :profile
        patch :profile
        post :register
        post :login
        delete :logout
      end
    end
  end
  root to: 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instance.rb
require 'securerandom'
class Instance < ApplicationRecord
  has_many :authentication_tokens, dependent: :destroy
  has_many :log_entries, dependent: :destroy
  has_many :toilet_definitions, dependent: :destroy
  validates :ident_str, presence: true, uniqueness: true
  validates :name, presence: true
  before_validation :generate_ident_str
  scope :filter, -> (filter) { where('UPPER(name) LIKE UPPER(?)', "%#{filter}%") }

  private

  def generate_ident_str
    if self.ident_str.blank?
      ident_str = SecureRandom.hex(10)
      while self.class.where(ident_str: ident_str).any?
        ident_str = SecureRandom.hex(10)
      end
      self.ident_str = ident_str
    end
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin
  before_action :find_instance, only: [:update, :destroy]

  def index
    @instances = Instance.all
    @instances = @instances.filter(params[:filter]) if params[:filter].present?
    @instances = @instances.order(:created_at)
    @new_instance = Instance.new
  end

  def create
    @instance = Instance.create(instance_params)
    if @instance.persisted?
      flash[:success] = 'Instancja dodana pomyślnie!'
    else
      flash[:error] = "Błąd przy dodawaniu instancji: #{@instance.errors.full_messages.join(',')}"
    end
    redirect_to instances_url
  end

  def update
    if @instance.update(instance_params)
      flash[:success] = 'Instancja zaktualizowana pomyślnie!'
    else
      flash[:error] = "Błąd przy aktualizacji instancji: #{@instance.errors.full_messages.join(',')}"
    end
    redirect_to instances_url
  end

  def destroy
    if @instance.destroy
      flash[:success] = 'Instancja usunięta pomyślnie!'
    else
      flash[:error] = "Błąd przy usuwaniu instancji: #{@instance.errors.full_messages.join(',')}"
    end
    redirect_to instances_url
  end

  private

  def find_instance
    @instance = Instance.find(params[:id])
  end

  def instance_params
    params.require(:instance).permit(:name, :description, :activation_needed_qsos, :activation_require_confirmation)
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/index.haml
%h3.mt-1 Instancje
= form_tag nil, method: :get, class: 'form-inline' do
  .form-group
    = text_field_tag :filter, params[:filter], placeholder: 'Nazwa...', class: 'form-control mr-2 mb-2'
  .form-group
    = submit_tag 'Filtruj', class: 'btn btn-primary mb-2'
%table.table.table-responsive.table-striped
  %thead.thead-dark
    %tr
      %th{scope: :col} Klucz identyfikacyjny
      %th{scope: :col} Nazwa
      %th{scope: :col} Opis
      %th{scope: :col} Liczba QSO wymaganych do ważności aktywacji
      %th{scope: :col} Wymagaj potwierdzonych QSO do aktywacji
      %th{scope: :col}
      %th{scope: :col}
  %tbody
    %tr.table-success
      = form_for @new_instance do |f|
        %td
          %span.form-text.text-muted (generowany automatycznie)
        %td= f.text_field :name, class: 'form-control'
        %td= f.text_area :description, rows: 5, class: 'form-control'
        %td= f.number_field :activation_needed_qsos, min: 1, step: 1, class: 'form-control'
        %td
          .form-check
            = f.check_box :activation_require_confirmation
        %td= f.submit 'Dodaj instancję', class: 'btn btn-success'
        %td
    - @instances.each do |instance|
      %tr
        = form_for instance do |f|
          %td
            %span.form-text= instance.ident_str
          %td= f.text_field :name, class: 'form-control'
          %td= f.text_area :description, rows: 5, class: 'form-control'
          %td= f.number_field :activation_needed_qsos, min: 1, step: 1, class: 'form-control'
          %td
            .form-check
              = f.check_box :activation_require_confirmation
          %td= f.submit 'Zapisz zmiany', class: 'btn btn-warning'
          %td= link_to 'Usuń', instance_path(instance), method: :delete, class: 'btn btn-danger', data: { confirm: 'Na pewno?' }