config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, path: :admin_users, only: [:index, :create, :update, :destroy]
  resources :log_entries, only: [:index, :create, :update, :destroy]
  resources :authentication_tokens, only: [:index, :destroy]
  resources :instances, only: [:index, :create, :update, :destroy]
  resources :toilet_definitions, only: [:index, :create, :update, :destroy]
  namespace :api do
    resources :log_entries, only: [:index, :create, :show, :update, :destroy] do
      collection do
        get :top
        get :activations
      end
    end
    resources :ranking, only: :none do
      collection do
        get :top
        get :my
      end
    end
    resources :toilet_definitions, only: [:index]
    resources :users, only: :none do
      collection do
        get :me
        put :profile
        patch :profile
        post :register
        post :login
        delete :logout
      end
    end
  end
  root to: 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/log_entry.rb
class LogEntry < ApplicationRecord
  belongs_to :user
  belongs_to :instance
  validates :callsign_from, presence: true, format: /([A-Z0-9]+\/)?(([0-9][A-Z][0-9][A-Z]{3})|([A-Z][0-9][A-Z]{1,3})|([A-Z]{2}[0-9][A-Z]{1,3}))((\/[A-z0-9]+)+)?/
  validates :callsign_to, presence: true, format: /([A-Z0-9]+\/)?(([0-9][A-Z][0-9][A-Z]{3})|([A-Z][0-9][A-Z]{1,3})|([A-Z]{2}[0-9][A-Z]{1,3}))((\/[A-z0-9]+)+)?/
  validates :band, presence: true, inclusion: { in: %w(160m 80m 60m 40m 30m 20m 17m 15m 12m 10m 6m 2m 70cm 23cm) }
  validates :mode, presence: true, inclusion: { in: ['CW', 'SSB', 'FM', 'Dane', 'AM', 'Inna emisja'] }
  validates :qso_at, presence: true
  validates :instance_id, presence: true
  validate :check_if_toilet_present, :check_if_not_the_same_toilet, :check_if_not_the_same_callsign, :check_for_double_chase, :check_for_double_activation_qso, :check_toilet_ids
  after_save :update_entry_confirmation


  private

  def check_if_toilet_present
    if toilet_id_from.blank? && toilet_id_to.blank?
      errors.add(:base, 'Toaleta rozmówcy i/lub Twoja toaleta musi być wybrana!')
    end
  end

  def check_if_not_the_same_toilet
    if toilet_id_from == toilet_id_to
      errors.add(:base, 'Toaleta rozmówcy i Twoja toaleta muszą mieć różne wartości!')
    end
  end

  def check_if_not_the_same_callsign
    if callsign_from == callsign_to
      errors.add(:base, "Znak wywoławczy rozmówcy i Twój znak wywoławczy muszą mieć różne wartości!")
    end
  end

  def check_for_double_activation_qso
    if toilet_id_to.present? && user.log_entries.where.not(id: id).where(toilet_id_to: toilet_id_to, callsign_from: callsign_from).where('qso_at >= ? AND qso_at <= ?', qso_at.to_time.utc.beginning_of_day, qso_at.to_time.utc.end_of_day).any?
      errors.add(:base, "Podwójne aktywacyjne QSO z tym samym znakiem nie jest możliwe!")
    end
  end

  def check_for_double_chase
    if toilet_id_from.present? && user.log_entries.where.not(id: id).where(toilet_id_from: toilet_id_from, callsign_from: callsign_from).where('qso_at >= ? AND qso_at <= ?', qso_at.to_time.utc.beginning_of_day, qso_at.to_time.utc.end_of_day).any?
      errors.add(:base, "Podwójne łowy tej samej toalety z tym samym znakiem nie są możliwe!")
    end
  end

  def update_entry_confirmation
    entry = self.class.where(callsign_from: self.callsign_to, callsign_to: self.callsign_from).where('toilet_id_from = ? OR toilet_id_to = ?', self.toilet_id_to, self.toilet_id_from).where('qso_at >= ? AND qso_at <= ?', self.qso_at - 5.minutes, self.qso_at + 5.minutes).first
    if entry.present?
      self.update_column(:confirmed, true)
      entry.update_column(:confirmed, true)
    else
      self.update_column(:confirmed, false)
    end
  end

  def check_toilet_ids
    if instance.present?
      toilet_ids = instance.toilet_definitions.pluck(:identifier)
      if toilet_id_from.present? && toilet_ids.exclude?(toilet_id_from)
        errors.add(:toilet_id_from, "musi mieć wartość ze zdefiniowanej listy")
      end
      if toilet_id_to.present? && toilet_ids.exclude?(toilet_id_to)
        errors.add(:toilet_id_to, "musi mieć wartość ze zdefiniowanej listy")
      end
    end
  end
end

app/controllers/api/log_entries_controller.rb
class Api::LogEntriesController < ApiController
  before_action :authorize_with_auth_header, except: :top
  before_action :find_instance, only: :top
  def top
    log_entries = @instance.log_entries.order(qso_at: :desc).limit(params[:limit])
    render json: LogEntrySerializer.new(log_entries).serializable_hash
  end

  def index
    log_entries = @current_user.log_entries.where(instance: @instance).order(qso_at: :desc)
    log_entries = log_entries.limit(params[:limit]) if params[:limit]
    render json: LogEntrySerializer.new(log_entries).serializable_hash
  end

  def activations
    activations = ActiveRecord::Base.connection.exec_query(Tota::AdvancedQueries.activations_query(@instance, @current_user)).to_a
    render json: { activations: activations }
  end

  def create
    log_entry = @current_user.log_entries.create(instance: @instance, callsign_from: params[:callsign_from], toilet_id_from: params[:toilet_id_from], callsign_to: params[:callsign_to], toilet_id_to: params[:toilet_id_to], band: params[:band], mode: params[:mode], qso_at: params[:qso_at])
    if log_entry.persisted?
      render json: { success: 'success', object: LogEntrySerializer.new(log_entry).serializable_hash }
    else
      render status: 422, json: { error: 'log_entry_validation', details: log_entry.errors.to_hash }
    end
  end

  def show
    log_entry = @current_user.log_entries.where(instance: @instance).find_by_id(params[:id])
    if log_entry.blank?
      render status: 404, json: { error: 'log_entry_not_found' } and return
    end
    render json: LogEntrySerializer.new(log_entry).serializable_hash
  end

  def update
    log_entry = LogEntry.find_by(user: @current_user, instance: @instance, id: params[:id])
    if log_entry.blank?
      render status: 404, json: { error: 'log_entry_not_found' } and return
    end
    if log_entry.update(callsign_from: params[:callsign_from], toilet_id_from: params[:toilet_id_from], callsign_to: params[:callsign_to], toilet_id_to: params[:toilet_id_to], band: params[:band], mode: params[:mode], qso_at: params[:qso_at])
      render json: { success: 'success', object: LogEntrySerializer.new(log_entry).serializable_hash }
    else
      render status: 422, json: { error: 'log_entry_validation', details: log_entry.errors.to_hash }
    end
  end

  def destroy
    log_entry = LogEntry.find_by(user: @current_user, instance: @instance, id: params[:id])
    if log_entry.blank?
      render status: 404, json: { error: 'log_entry_not_found' } and return
    end
    if log_entry.destroy
      render json: { success: 'success' }
    else
      render status: 422, json: { error: 'log_entry_validation', details: log_entry.errors.to_hash }
    end
  end
end

app/controllers/log_entries_controller.rb
require 'date'
class LogEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin
  before_action :find_log_entry, only: [:update, :destroy]
  def index
    @log_entries = LogEntry.all
    @log_entries = @log_entries.where(instance_id: params[:instance_id]) if params[:instance_id].present?
    @log_entries = @log_entries.where(user_id: params[:user_id]) if params[:user_id].present?
    @log_entries = @log_entries.order(instance_id: :asc, user_id: :asc, qso_at: :desc)
    @instances = Instance.order(name: :asc)
    @users = User.order(login: :asc)
  end

  def update
    if @log_entry.update(log_entry_params)
      flash[:success] = 'QSO zaktualizowane pomyślnie!'
    else
      flash[:error] = "Błąd przy aktualizacji QSO: #{@log_entry.errors.full_messages.join(',')}"
    end
    redirect_to log_entries_url
  end

  def destroy
    if @log_entry.destroy
      flash[:success] = 'QSO usunięte pomyślnie!'
    else
      flash[:error] = "Błąd przy usuwaniu QSO: #{@log_entry.errors.full_messages.join(',')}"
    end
    redirect_to log_entries_url
  end

  private

  def find_log_entry
    @log_entry = LogEntry.find(params[:id])
  end

  def log_entry_params
    params.require(:log_entry).permit(:callsign_from, :toilet_id_from, :callsign_to, :toilet_id_to, :band, :mode, :qso_at)
  end
end

app/helpers/api/log_entries_helper.rb
module Api::LogEntriesHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/views/log_entries/index.haml
%h3.mt-1 Zalogowane QSO
= form_tag nil, method: :get, class: 'form-inline' do
  .form-group
    = select_tag :instance_id, options_from_collection_for_select(@instances, :id, :name, params[:instance_id]), include_blank: 'Wybierz instancję...', class: 'custom-select mr-2 mb-2'
  .form-group
    = select_tag :user_id, options_from_collection_for_select(@users, :id, :login, params[:user_id]), include_blank: 'Wybierz użytkownika...', class: 'custom-select mr-2 mb-2'
  .form-group
    = submit_tag 'Filtruj', class: 'btn btn-primary mb-2'
%table.table.table-responsive.table-striped
  %thead.thead-dark
    %tr
      %th{scope: :col} Instancja
      %th{scope: :col} Użytkownik
      %th{scope: :col} Znak wywoławczy nadawcy
      %th{scope: :col} Toaleta nadawcy
      %th{scope: :col} Znak wywoławczy odbiorcy
      %th{scope: :col} Toaleta odbiorcy
      %th{scope: :col} Pasmo
      %th{scope: :col} Emisja
      %th{scope: :col} Data i godzina (UTC)
      %th{scope: :col}
      %th{scope: :col}
  %tbody
    - @log_entries.each do |log_entry|
      %tr{class: log_entry.confirmed? ? 'table-success' : ''}
        = form_for log_entry do |f|
          %td
            %span.form-text= log_entry.instance.name
          %td
            %span.form-text= log_entry.user.login
          %td= f.text_field :callsign_to, class: 'form-control'
          %td= f.text_field :toilet_id_to, class: 'form-control'
          %td= f.text_field :callsign_from, class: 'form-control'
          %td= f.text_field :toilet_id_from, class: 'form-control'
          %td= f.select :band, options_for_select((%w(160m 80m 60m 40m 30m 20m 17m 15m 12m 10m 6m 2m 70cm 23cm).map { |b| [b,b] }), log_entry.band), {}, class: 'custom-select'
          %td= f.select :mode, options_for_select((['CW', 'SSB', 'FM', 'Dane', 'AM', 'Inna emisja'].map { |m| [m,m] }), log_entry.mode), {}, class: 'custom-select'
          %td= f.text_field :qso_at, value: log_entry.qso_at.utc.strftime('%d-%m-%Y %H:%M'), class: 'form-control'
          %td= f.submit 'Zapisz zmiany', class: 'btn btn-warning'
          %td= link_to 'Usuń',log_entry_path(log_entry) , method: :delete, class: 'btn btn-danger', data: { confirm: 'Na pewno?' }