config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, path: :admin_users, only: [:index, :create, :update, :destroy]
  resources :log_entries, only: [:index, :create, :update, :destroy]
  resources :authentication_tokens, only: [:index, :destroy]
  resources :instances, only: [:index, :create, :update, :destroy]
  resources :toilet_definitions, only: [:index, :create, :update, :destroy]
  namespace :api do
    resources :log_entries, only: [:index, :create, :show, :update, :destroy] do
      collection do
        get :top
        get :activations
      end
    end
    resources :ranking, only: :none do
      collection do
        get :top
        get :my
      end
    end
    resources :toilet_definitions, only: [:index]
    resources :users, only: :none do
      collection do
        get :me
        put :profile
        patch :profile
        post :register
        post :login
        delete :logout
      end
    end
  end
  root to: 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:callsign])
    devise_parameter_sanitizer.permit(:account_update, keys: [:callsign])
  end

  def ensure_admin
    if user_signed_in? && !current_user.admin?
      flash[:error] = 'Musisz mieć uprawnienia administratora'
      sign_out current_user
      redirect_to new_user_session_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_alerts.haml
- if flash[:notice]
  .alert.alert-info.alert-dismissible.fade.show{role: 'alert'}
    = flash[:notice]
    %button.close{type: :button, data: {dismiss: :alert}, 'aria-label': :Close}
      %span{'aria-hidden': :true}= '&times;'.html_safe
- if flash[:success]
  .alert.alert-success.alert-dismissible.fade.show{role: 'alert'}
    = flash[:success]
    %button.close{type: :button, data: {dismiss: :alert}, 'aria-label': :Close}
      %span{'aria-hidden': :true}= '&times;'.html_safe
- if flash[:error]
  .alert.alert-danger.alert-dismissible.fade.show{role: 'alert'}
    = flash[:error]
    %button.close{type: :button, data: {dismiss: :alert}, 'aria-label': :Close}
      %span{'aria-hidden': :true}= '&times;'.html_safe
- if flash[:alert]
  .alert.alert-danger.alert-dismissible.fade.show{role: 'alert'}
    = flash[:alert]
    %button.close{type: :button, data: {dismiss: :alert}, 'aria-label': :Close}
      %span{'aria-hidden': :true}= '&times;'.html_safe

app/views/application/_footer.haml
.footer.text-center.border-top
  %small Created by Phitherek_ SO9PH in 2018

app/views/application/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to "TOTA Admin", root_path, class: 'navbar-brand'
  %button.navbar-toggler{type: :button, data: {toggle: :collapse, target: '#mainNavbarContent'}, 'aria-controls': 'mainNavbarContent', 'aria-expanded': :false, 'aria-label': 'Przełącz nawigację'}
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#mainNavbarContent
    %ul.navbar-nav.mr-auto
      - if current_user
        %li.nav-iem
          = link_to 'Użytkownicy', users_path, class: "nav-link #{controller_name == 'users' ? 'active' : ''}", data: { turbolinks: false }
        %li.nav-item
          = link_to 'Instancje', instances_path, class: "nav-link #{controller_name == 'instances' ? 'active' : ''}", data: { turbolinks: false }
        %li.nav-item
          = link_to 'Definicje toalet', toilet_definitions_path, class: "nav-link #{controller_name == 'toilet_definitions' ? 'active' : ''}", data: { turbolinks: false }
        %li.nav-item
          = link_to 'Tokeny autoryzacji', authentication_tokens_path, class: "nav-link #{controller_name == 'authentication_tokens' ? 'active' : ''}", data: { turbolinks: false }
        %li.nav-item
          = link_to 'Zalogowane QSO', log_entries_path, class: "nav-link #{controller_name == 'log_entries' ? 'active' : ''}", data: { turbolinks: false }
    - if current_user
      %ul.navbar-nav
        %li.nav-item
          %span.navbar-text Zalogowano jako #{current_user.callsign}
        %li.nav-item
          = link_to "Wyloguj", destroy_user_session_path, class: 'nav-link', method: :delete, data: { turbolinks: false }
    - else
      %ul.navbar-nav
        %li.nav-item
          %span.navbar-text Nie zalogowano
        %li.nav-item
          = link_to "Logowanie", new_user_session_path, class: 'nav-link', data: { turbolinks: false }