config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, path: :admin_users, only: [:index, :create, :update, :destroy]
  resources :log_entries, only: [:index, :create, :update, :destroy]
  resources :authentication_tokens, only: [:index, :destroy]
  resources :instances, only: [:index, :create, :update, :destroy]
  resources :toilet_definitions, only: [:index, :create, :update, :destroy]
  namespace :api do
    resources :log_entries, only: [:index, :create, :show, :update, :destroy] do
      collection do
        get :top
        get :activations
      end
    end
    resources :ranking, only: :none do
      collection do
        get :top
        get :my
      end
    end
    resources :toilet_definitions, only: [:index]
    resources :users, only: :none do
      collection do
        get :me
        put :profile
        patch :profile
        post :register
        post :login
        delete :logout
      end
    end
  end
  root to: 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/toilet_definition.rb
class ToiletDefinition < ApplicationRecord
  belongs_to :instance
  validates :identifier, presence: true, uniqueness: { scope: :instance_id }
  validates :points, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/controllers/api/toilet_definitions_controller.rb
class Api::ToiletDefinitionsController < ApiController
  before_action :find_instance

  def index
    toilet_definitions = @instance.toilet_definitions.order(identifier: :asc)
    render json: ToiletDefinitionSerializer.new(toilet_definitions).serializable_hash
  end
end

app/controllers/toilet_definitions_controller.rb
class ToiletDefinitionsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin
  before_action :find_toilet_definition, only: [:update, :destroy]

  def index
    @toilet_definitions = ToiletDefinition.all
    @toilet_definitions = @toilet_definitions.where(instance: Instance.find(params[:instance_id])) if params[:instance_id].present?
    @toilet_definitions = @toilet_definitions.order(instance_id: :asc, created_at: :desc)
    @new_toilet_definition = ToiletDefinition.new
    @instances = Instance.order(name: :asc)
  end

  def create
    @toilet_definition = ToiletDefinition.create(toilet_definition_params)
    if @toilet_definition.persisted?
      flash[:success] = 'Definicja toalety dodana pomyślnie!'
    else
      flash[:error] = "Błąd przy dodawaniu definicji toalety: #{@toilet_definition.errors.full_messages.join(', ')}"
    end
    redirect_to toilet_definitions_url
  end

  def update
    if @toilet_definition.update(toilet_definition_params)
      flash[:success] = 'Definicja toalety zaktualizowana pomyślnie!'
    else
      flash[:error] = "Błąd przy aktualizacji definicji toalety: #{@toilet_definition.errors.full_messages.join(', ')}"
    end
    redirect_to toilet_definitions_url
  end

  def destroy
    if @toilet_definition.destroy
      flash[:success] = 'Definicja toalety usunięta pomyślnie!'
    else
      flash[:error] = "Błąd przy usuwaniu definicji toalety: #{@toilet_definition.errors.full_messages.join(', ')}"
    end
    redirect_to toilet_definitions_url
  end

  private

  def find_toilet_definition
    @toilet_definition = ToiletDefinition.find(params[:id])
  end

  def toilet_definition_params
    params.require(:toilet_definition).permit(:instance_id, :identifier, :points)
  end
end

app/helpers/api/toilet_definitions_helper.rb
module Api::ToiletDefinitionsHelper
end

app/helpers/toilet_definitions_helper.rb
module ToiletDefinitionsHelper
end

app/views/toilet_definitions/index.haml
%h3.mt-1 Definicje toalet
= form_tag nil, method: :get, class: 'form-inline' do
  .form-group
    = select_tag :instance_id, options_from_collection_for_select(@instances, :id, :name, params[:instance_id]), include_blank: 'Wybierz instancję...', class: 'custom-select mr-2 mb-2'
  .form-group
    = submit_tag 'Filtruj', class: 'btn btn-primary mb-2'
%table.table.table-responsive.table-striped
  %thead.thead-dark
    %tr
      %th{scope: :col} Instancja
      %th{scope: :col} Identyfikator
      %th{scope: :col} Liczba punktów
      %th{scope: :col}
      %th{scope: :col}
  %tbody
    %tr.table-success
      = form_for @new_toilet_definition do |f|
        %td= f.collection_select :instance_id, @instances, :id, :name, {selected: params[:instance_id], include_blank: 'Wybierz instancję...'}, {class: 'custom-select'}
        %td= f.text_field :identifier, class: 'form-control'
        %td= f.number_field :points, min: 1, step: 1, class: 'form-control'
        %td= f.submit 'Dodaj definicję toalety', class: 'btn btn-success'
        %td
    - @toilet_definitions.each do |toilet_definition|
      %tr
        = form_for toilet_definition do |f|
          %td
            %span.form-text= toilet_definition.instance.name
          %td= f.text_field :identifier, class: 'form-control'
          %td= f.number_field :points, min: 1, step: 1, class: 'form-control'
          %td= f.submit 'Zapisz zmiany', class: 'btn btn-warning'
          %td= link_to 'Usuń', toilet_definition_path(toilet_definition), method: :delete, class: 'btn btn-danger', data: { confirm: 'Na pewno?' }